name: Trie
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/trie

defaults:
  run:
    working-directory: packages/trie

jobs:
  test-trie:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          key: Trie-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          path: '**/node_modules'

      # Installs root dependencies, ignoring Bootstrap All script.
      # Bootstraps the current package only
      - run: npm install --ignore-scripts && npm run bootstrap:trie
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}

      # Builds current package and the ones it depends from.
      - run: npm run build:trie
        working-directory: ${{github.workspace}}

      - run: npm run coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: trie
        if: ${{ matrix.node-version == 12 }}

      - run: npm run lint

  trie-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          key: Trie-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          path: '**/node_modules'
      
      # Installs root dependencies, ignoring Bootstrap All script.
      # Bootstraps the current package only
      - run: npm install --ignore-scripts && npm run bootstrap:trie
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}
      
      - run: npm run benchmarks | tee output.txt
        working-directory: ${{ env.cwd }}

      # Run git stash in case github-action-benchmark has trouble switching to gh-pages branch due to differing package-locks
      - run: git stash

      - name: Compare benchmarks
        uses: rhysd/github-action-benchmark@v1
        if: github.ref == 'refs/heads/master'
        with:
          tool: 'benchmarkjs'
          # Where the output from the benchmark tool is stored
          output-file-path: ${{ env.cwd }}/output.txt
          # Location of data in gh-pages branch
          benchmark-data-dir-path: dev/bench/trie
          # Enable alert commit comment
          comment-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy to GitHub pages branch automatically (if on master)
          auto-push: ${{ github.ref == 'refs/heads/master' }}
          # Only keep and display the last 30 commits worth of benchmark data
          max-items-in-chart: 30

      # Re-apply git stash to prepare for saving back to cache.
      # Avoids exit code 1 by checking if there are changes to be stashed first
      - run: STASH_LIST=`git stash list` && [ ! -z $STASH_LIST ] && git stash apply || echo "No files to stash-apply. Skipping…"
